version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: SpacyNLP
  model: "en_core_web_sm"
- name: SpacyEntityExtractor
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  embedding_dimension: 50
  learning_rate: 0.002
  constrain_similarities: true
  dropout: 0.2
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 200
  retrieval_intent: "faq"
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.05


policies:
- name: RulePolicy
- name: TEDPolicy
  max_history: 10
  epochs: 150
- name: AugmentedMemoizationPolicy
  core_fallback_action_name: "action_fallback_llm"
  nlu_threshold: 0.3
  core_fallback_threshold: 0.3
  deny_suggestion_intent_name: "out_of_scope"
assistant_id: 20250313-184318-roaring-bosun
