version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer    # Tokenizer added before featurizers
- name: SpacyNLP
  model: "en_core_web_sm"    # Ensure you have the right spaCy model
- name: SpacyEntityExtractor
- name: RegexEntityExtractor    # Optional, can be removed if not needed
- name: RegexFeaturizer    # Featurizer
- name: CountVectorsFeaturizer    # Featurizer
- name: CountVectorsFeaturizer    # Featurizer with ngram features
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: AugmentedMemoizationPolicy
  core_fallback_action_name: "action_fallback_llm"
  nlu_threshold: 0.7
  core_fallback_threshold: 0.3
  deny_suggestion_intent_name: "out_of_scope"
assistant_id: 20250303-170548-antique-coverage
